#!/bin/bash
# This file is part of the Kojoney2 honeypot
#
# Main Developer - Justin C. Klein Keane <jukeane@sas.upenn.edu>
# Original Developer - Jose Antonio Coret <joxeankoret@yahoo.es>
# Last updated 28 January, 2013
#
# Kojoney reporting script

version=0.0.4
tools_dir=`dirname $0`

function show_authenticated
{
	cat $1 | grep "$2" | awk '{ print $7 }' | sort | uniq -c | sort -r -g
	echo
	echo Total `cat $1 | grep "$2" | awk '{ print $7 }' | wc -l`
}

function show_unauthenticated
{
	cat $1 | grep "$2" | awk '{ print $4 }' | sort | uniq -c | sort -r -g
	echo
	echo Total `cat $1 | grep "$2" | awk '{ print $4 }' | wc -l`
}

function show_total
{
	echo Total `cat $1 | grep "$2" | wc -l`
}

function show_commands
{
	cat $1 | grep 'COMMAND IS' | awk '{ print $14" "$15" "$16" "$17" "$18" "$19" "$20" "$21" "$22" "$23" "$24" "$25 }' \
		| sort | uniq -c | sort -r -g
	echo
	echo Total `cat $1 | grep 'COMMAND IS' | \
		awk '{ print $15" "$16" "$17" "$18" "$19" "$20" "$21" "$22" "$23" "$24" "$25" "$26" "$27 }' | wc -l`
}

function show_commands_by_session
{
	$tools_dir/sessions_with_commands "$1" | xargs -i $tools_dir/commands_by_session_and_ip $1 {}
}

function show_ip_address
{
	ips=`cat $1 | grep 'kex alg, key alg' | grep SSHServerTransport | awk '{ print $3 }' |awk -F, '{ print $3 }' | \
		awk -F] '{ print $1 }' | sort | uniq | sort -r -g`

	i=0
	for ip in $ips
	do
		i=`expr $i + 1`

		echo -e "   $i\t$ip - `cat $1 | grep $ip | grep 'authenticated with' | wc -l ` connection(s)"
		/usr/bin/python $tools_dir/kip2country.py $ip
		
	done

	echo
	echo Total $i
}

function show_passwords
{
	#cat $1 | grep "$2" -A1 | awk '{ user=$8; getline; pws=""; x=10; while (x <= NF) {pws = (pws $x " "); x++} print user ": " pws; getline;}' | sort
	cat $1 | grep "$2" | awk '{print $14 ": " $15;}' | sort	
	echo ""
	echo Total `cat $1 | grep "$2" | wc -l`
}

function show_usage
{
	echo "Kojoney2 Honeypot general report generator $version"
	echo "Modified by Justin C. Klein Keane"
	echo "Original Copyright (c) 2005 Jose Antonio Coret"
	echo
	echo -e "Usage: $0 file <traceroute> <nmap> <country>"
	echo
	echo Options:
	echo
	echo -e "<traceroute>  Print the route packets take to network host"
	echo -e "              Value must be 0 (disabled) or 1 (enabled)"
	echo -e "<nmap>        Print nmap output take to network host"
	echo -e "              Value must be 0 (disabled) or 1 (enabled)"
	echo -e "<country>     Resolve intruder's country"
	echo -e "              Value must be 0 (disabled) or 1 (enabled)"
	echo
	echo
	exit 0
}

if [ $# -eq 0 ]; then
	show_usage
fi

echo Kojoney2 Honeypot Report
echo -----------------------
echo
echo Date: `date +%c`
echo Log lines: `cat $1 | wc -l`
echo Log size: `du -h $1`
echo
echo Number of times a remote shell was opened
echo -----------------------------------------
echo
show_total $1 'getting shell'
echo 

echo Executed commands by session
echo ----------------------------
echo
show_commands_by_session $1
echo

echo IP Addresses
echo ------------
echo 
show_ip_address $1 'SSHServerTransport' 0 0 0
echo

echo Authenticated users. Successful logons
echo ---------------------------------------
echo
show_authenticated $1 'authenticated with password'
echo

echo Unauthenticated users. Failed logons
echo ------------------------------------
echo
show_unauthenticated $1 'failed auth password'
echo

#echo Users successfully authenticated with publickey
#echo ------------------------------------------------
#echo
#show_authenticated $1 'authenticated with publickey'
#echo
#echo Users unsuccessfully authenticated with publickey
#echo --------------------------------------------------
#echo 
#show_unauthenticated $1 'failed auth publickey'
#echo
#echo Logons with null passwords
#echo --------------------------
#echo
#show_authenticated $1 'trying auth none'
#echo
#echo Logons with or without password
#echo -------------------------------
#echo
#show_authenticated $1 'trying auth'
#echo
#echo X11 forward requests
#echo --------------------
#echo 
#show_total $1 'request for x11'
#echo
#echo Executed different commands
#echo ---------------------------
#echo
#show_commands $1 
#echo
#echo Number of times the intruder tries to change the terminal window size 
#echo ---------------------------------------------------------------------
#echo
#show_total $1 'error changing window size'
#echo
#
#if [ $# -gt 1 ]; then
#    if [ $2 -eq 1 ]; then
#	echo Traceroute to intruders hosts
#	echo ------------------------------
#	echo
#	show_ip_address $1 'SSHServerTransport' 1 0 0
#	echo
#    fi
#fi
#
#if [ $# -gt 2 ]; then
#    if [ $3 -eq 1 ]; then
#	echo NMap scan against intruders hosts
#	echo ----------------------------------
#	echo
#	show_ip_address $1 'SSHServerTransport' 0 1 0
#	echo
#    fi
#fi
#
#if [ $# -gt 3 ]; then
#    if [ $4 -eq 1 ]; then
#    	echo IP Addresses and Countries
#	echo --------------------------
#	echo
#	show_ip_address $1 'SSHServerTransport' 0 0 1
#	echo
#    fi
#fi
#
#echo Sessions opened by humans
#echo -------------------------
#echo
#$tools_dir/kojhumans $1 --by-session
#echo
#echo Humans detecteds by IP
#echo ----------------------
#$tools_dir/kojhumans $1 --by-ip
#echo
#echo Internal Honeypot Errors
#echo ------------------------
#echo
#show_total $1 '<exception caught here>'
#echo
#echo Passwords used for each user
#echo ------------------------
#echo
#show_passwords $1 'Login attempt with this username and password:'

