.TH "kip2country" "1" "0.0.2" "Jose Antonio Coret" "Tools"
.SH "NAME"
.LP 
kip2country \- Lookup Country by IP Address.
.SH "SYNTAX"
.LP 
kip2country \fIip\fP [\fIip2\fP] [\fIip3\fP] ...
.SH "DESCRIPTION"
.LP 
Lookup Country by IP Address.
.SH "EXAMPLES"
.LP 
$ kip2country www.honeypot.co.uk 
.LP 
DE, Germany
.LP 
$ kip2country 66.35.250.150 
.LP 
US, United States
.SH "AUTHORS"
.LP 
Jose Antonio Coret <joxeankoret@yahoo.es>
.SH "SEE ALSO"
.LP 
kojreport(1) kojreport\-filter(1) kojhumans(1)
