doc:
	man2html man/kip2country.1 | grep -v 'Content-type:' > html/kip2country.html
	man2html man/kojreport.1 | grep -v 'Content-type:' > html/kojreport.html
	man2html man/kojreport-filter.1 | grep -v 'Content-type:' > html/kojreport-filter.html
	man2html man/kojhumans.1 | grep -v 'Content-type:' > html/kojhumans.html
clean:
	rm -f html/*
