#!/bin/bash
# This file is part of the Kojoney2 honeypot
#
# Main Developer - Justin C. Klein Keane <jukeane@sas.upenn.edu>
# Original Developer - Jose Antonio Coret <joxeankoret@yahoo.es>
# Last updated 23 July 2014
#
# chkconfig: 2345 99 15
# description: Starts and stops OSSEC HIDS (Host Intrusion Detection System)
#
# This will work on Redhat systems (maybe others too)

set -e

# /etc/init.d/ssh: start and stop the Koret honeypot for the "secure shell(tm)" protocol

test -x /usr/bin/kojoneyd || exit 0

case "$1" in
  start)
        echo -n "Starting Kojoney2 Honeypot: kojoneyd"
	/usr/bin/kojoneyd 2>&1 >/dev/null&
        echo "."
	;;
  stop)
        echo -n "Stopping Kojoney2 Honeypot: kojoneyd"
	kill `ps aux | grep /usr/bin/kojoney | grep -v grep | awk '{ print $2 }'`
        echo "."
	;;

  kill)
        echo -n "Killing Kojoney2 Honeypot: kojoneyd"
	kill -9 `ps aux | grep /usr/bin/kojoneyd | grep -v grep | awk '{ print $2 }'`
        echo "."
	;;

   restart)
        echo -n "Restarting Kojoney2 Honeypot: kojoneyd"
        /etc/init.d/kojoney stop > /dev/null
        /etc/init.d/kojoney start > /dev/null
        echo "."
        ;;

  status)
	value=`ps aux | grep /usr/bin/kojoneyd | grep -v grep | wc -l`

	if [ $value -eq 0 ]; then
		echo "Server is stopped."
	else
		echo "Server is up and running."
	fi
	;;
  *)
	echo "Usage: /etc/init.d/kojoney {start|stop|kill|restart|status}"
	exit 1
esac

exit 0
